// <auto-generated />
namespace CBE.Feature.DiscussionForum.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addstotablesnames : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addstotablesnames));
        
        string IMigrationMetadata.Id
        {
            get { return "202201091814204_add s to tables names"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
